import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import { TiThMenu } from "react-icons/ti";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import { IoIosArrowDown } from "react-icons/io";
import logo from '../../public/eye.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eye Clinic | bradford',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en" className=''>
      <body className={inter.className}>
      <div className='sticky top-0 z-50'> 
        <div className=' top-0 z-50'>
    <header className='flex justify-between px-6 py-2  bg-white shadow-xl'>
      {/* left */}
      <div className='' >
        <h1  className='flex '>
        <Image className='rounded-xl mx-4 ' src={logo} alt='LOGO'width={80 } height={20} />
        
        </h1>
      </div>
      {/* right */}
        <div className=' transition-all'>
          <ul className='md:flex justify-evenly gap-x-5 px-6 py-3 font-semibold hidden transition-all  '>
            <li  className='hover:text-yellow-500  hover:underline text-black'><Link href={"/"} >Home  </Link></li>
            <li className='hover:text-yellow-500 hover:underline text-black'><Link href={"/eyetest"} > Eye Test </Link></li>
            <li className='hover:text-yellow-500 hover:underline text-black'><Link href={"/glasses"} > Glasses </Link></li>
            <li className='hover:text-yellow-500 hover:underline text-black'><Link href={"/contact-lenses"} >Contact lenses </Link></li>
            <li className='hover:text-yellow-500 hover:underline text-black'><Link href={"/childerns"} > Childerns </Link></li>
            <li className='relative flex items-center group transition-all   '><Link className=' text-black items-center cursor-pointer group-hover:tex transition-all hover:text-yellow-500' href={"/"} >myopia
              {/* dropdown */}
              <div className='absolute right-2 top-6 hidden w-40 flex-col gap-2 rounded-xl bg-white py-1 shadow-2xl  text-black transition-all group-hover:flex '>
              <Link className='mx-1 hover:text-yellow-400 hover:bg-black ' href={"/myopia"}>What is myopia</Link>
              <Link className='mx-1 hover:text-yellow-400 hover:bg-black ' href={"/misright-myopia"}>Misight 1 day contact lenses</Link>
              <Link className='mx-1 hover:text-yellow-400 hover:bg-black ' href={"/myosmart-lence"}>Miyosmart lanses</Link>
              </div>
            </Link>
            <IoIosArrowDown className='rotate-180 text-amber-300 transition-all  group-hover:rotate-0 ' />
            </li>
            <li className='hover:text-yellow-500 text-black'><Link href={"/contact"} >Contact  </Link></li>
            
          </ul>
            
          
          <div className='md:hidden flex sticky'>
          <Sheet >
<SheetTrigger>
<div className='items-center py-3.5 text-xl'>
<TiThMenu />
</div>
</SheetTrigger>
<SheetContent className='bg-blue-900 h-[19rem] rounded-xl gap-x-1'>
<SheetHeader className='space-y-5'>
<ul className='    gap-x- font-semibold  '>
            <li  className=' hover:text-white'>
              <Link href={"/"} >Home </Link>
               </li>
            <li className='hover:text-white'>
              <Link href={"/eyetest"} >Eye Test </Link>
              </li>
            <li className='hover:text-white'>
              <Link href={"/glasses"}>Glasses </Link>
               </li>
            <li className='hover:text-white'>
              <Link href={"/contact-lenses"} >Contact lenses </Link>
               </li>
               <li className='hover:text-white'>
              <Link href={"#childerns"} >Chidrens </Link>
               </li>
               <li className='relative flex group transition-all   '><Link className=' text-center mx-[5rem] cursor-pointer group-hover:text-white transition-all hover:text-white ' href={"/myopia"} >  myopia
              {/* dropdown */}
              <div className=' absolute right-0 top-6 hidden w-auto flex-col py-1 pl-6 gap-2 rounded-lg bg-blue-950 shadow-md text-amber-300 transition-all group-hover:flex '>
              <Link className='mx-1 hover:text-white ' href={"/myopia"}>What is myopia</Link>
              <Link className='mx-1 hover:text-white ' href={"/myosmart-lence"}>Misight 1 day contact lenses</Link>
              <Link className='mx-1 hover:text-white ' href={"/misright-myopia"}>Miyosmart lanses</Link>
              </div>
            </Link>
            <div className='flex'>

            <IoIosArrowDown className='rotate-180 items-center  transition-all  group-hover:rotate-0 ' />
            </div>

            </li>
               <li className='hover:text-white'>
              <Link href={"/contact"} >Contact </Link>
               </li>
          </ul>
</SheetHeader>
</SheetContent>
</Sheet>
        </div>


        </div>

    </header>

    </div>
    </div>
        {children}

      </body>
    </html>
  )
}
